#!/usr/bin/env python3
"""Generate API documentation markdown from FastAPI OpenAPI schema."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import json
import sys


ROOT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT_DIR / "backend"
OUTPUT_PATH = ROOT_DIR / "docs" / "content" / "api-reference.md"

METHOD_ORDER = ["get", "post", "put", "patch", "delete", "options", "head"]


def _format_type(schema: dict) -> str:
    schema_type = schema.get("type")
    if schema_type == "array":
        item_type = _format_type(schema.get("items", {}))
        return f"array<{item_type}>"
    if schema_type:
        return schema_type
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(_format_type(item) for item in schema["anyOf"])
    return "object"


def _schema_to_markdown(name: str, schema: dict) -> str:
    lines: list[str] = [f"### `{name}`", ""]
    schema_type = _format_type(schema)
    description = schema.get("description", "No description.")
    lines.append(f"- **Type:** `{schema_type}`")
    lines.append(f"- **Description:** {description}")
    lines.append("")

    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    if properties:
        lines.append("| Field | Type | Required | Description |")
        lines.append("| --- | --- | --- | --- |")
        for field_name, field_schema in sorted(properties.items()):
            field_type = _format_type(field_schema)
            field_required = "yes" if field_name in required else "no"
            field_description = field_schema.get("description", "")
            lines.append(
                f"| `{field_name}` | `{field_type}` | {field_required} | {field_description} |"
            )
        lines.append("")
    return "\n".join(lines)


def _endpoint_to_markdown(path: str, method: str, operation: dict) -> str:
    method_upper = method.upper()
    summary = operation.get("summary", "No summary")
    description = operation.get("description", "")
    operation_id = operation.get("operationId", "N/A")

    lines: list[str] = [f"### `{method_upper} {path}`", "", f"**Summary:** {summary}"]
    lines.append(f"**Operation ID:** `{operation_id}`")
    if description:
        lines.append("")
        lines.append(description)

    parameters = operation.get("parameters", [])
    if parameters:
        lines.append("")
        lines.append("**Parameters**")
        lines.append("")
        lines.append("| Name | In | Required | Type | Description |")
        lines.append("| --- | --- | --- | --- | --- |")
        for param in parameters:
            param_schema = param.get("schema", {})
            param_type = _format_type(param_schema)
            lines.append(
                f"| `{param.get('name', '')}` | `{param.get('in', '')}` | "
                f"{'yes' if param.get('required') else 'no'} | `{param_type}` | "
                f"{param.get('description', '')} |"
            )

    request_body = operation.get("requestBody")
    if request_body:
        lines.append("")
        lines.append("**Request Body**")
        lines.append("")
        lines.append(f"- Required: {'yes' if request_body.get('required') else 'no'}")
        content = request_body.get("content", {})
        for mime, mime_schema in content.items():
            schema = mime_schema.get("schema", {})
            lines.append(f"- `{mime}`: `{_format_type(schema)}`")

    responses = operation.get("responses", {})
    if responses:
        lines.append("")
        lines.append("**Responses**")
        lines.append("")
        lines.append("| Status | Description | Content Types |")
        lines.append("| --- | --- | --- |")
        for status_code, response in sorted(
            responses.items(), key=lambda item: item[0]
        ):
            content_types = ", ".join(sorted(response.get("content", {}).keys())) or "-"
            lines.append(
                f"| `{status_code}` | {response.get('description', '')} | {content_types} |"
            )

    lines.append("")
    return "\n".join(lines)


def _load_openapi_schema() -> dict:
    sys.path.insert(0, str(BACKEND_DIR))
    from main import app  # type: ignore

    return app.openapi()


def build_markdown(schema: dict) -> str:
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    info = schema.get("info", {})
    title = info.get("title", "API")
    version = info.get("version", "unknown")
    description = info.get("description", "")

    lines: list[str] = [
        "---",
        'title: "API Reference"',
        'description: "Auto-generated API documentation from FastAPI OpenAPI schema"',
        "---",
        "",
        f"> Auto-generated by `scripts/generate_api_docs.py` on `{generated_at}`.",
        "",
        "## OpenAPI Endpoints",
        "",
        f"- **Title:** {title}",
        f"- **Version:** `{version}`",
        f"- **OpenAPI JSON:** `GET /openapi.json`",
        f"- **Swagger UI:** `GET /docs`",
        f"- **ReDoc:** `GET /redoc`",
        "",
    ]

    if description:
        lines.extend([description, ""])

    lines.extend(["## Endpoints", ""])
    paths = schema.get("paths", {})
    for path in sorted(paths.keys()):
        path_item = paths[path]
        for method in METHOD_ORDER:
            if method in path_item:
                lines.append(_endpoint_to_markdown(path, method, path_item[method]))

    components = schema.get("components", {})
    schemas = components.get("schemas", {})
    if schemas:
        lines.extend(["## Schemas", ""])
        for name, schema_obj in sorted(schemas.items()):
            lines.append(_schema_to_markdown(name, schema_obj))

    return "\n".join(lines).strip() + "\n"


def main() -> None:
    schema = _load_openapi_schema()
    markdown = build_markdown(schema)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(markdown, encoding="utf-8")

    openapi_path = ROOT_DIR / "docs" / "static" / "openapi.json"
    openapi_path.write_text(json.dumps(schema, indent=2), encoding="utf-8")

    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT_DIR)}")
    print(f"Wrote {openapi_path.relative_to(ROOT_DIR)}")


if __name__ == "__main__":
    main()
